// @vitest-environment node
import { execFileSync } from 'node:child_process';
import { cpSync, existsSync, lstatSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, readlinkSync, rmSync, symlinkSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { check, generate, permissionProblems, write } from '../harness/sync-adapters.mjs';

const harnessSource = path.resolve(import.meta.dirname, '..', 'harness');
// The production commands come from .agents/harness.config.json.
const PRODUCTION_COMMANDS = ['acme deploy', 'acme db push'];
const roots = [];

// The package's harness/ copied to .agents/ of a temporary repository, as
// install.mjs does.
function installed(config = null) {
  const root = mkdtempSync(path.join(tmpdir(), 'agent-adapters-installed-'));
  roots.push(root);
  cpSync(harnessSource, path.join(root, '.agents'), { recursive: true });
  if (config) writeFileSync(path.join(root, '.agents/harness.config.json'), JSON.stringify(config));
  return root;
}

afterEach(() => {
  for (const root of roots.splice(0)) rmSync(root, { recursive: true, force: true });
});

function harness() {
  const root = mkdtempSync(path.join(tmpdir(), 'agent-adapters-'));
  roots.push(root);
  const files = {
    '.agents/rules/base.md': '# Base\n\n1. Rule.\n',
    '.agents/agents/reviewer.md': '---\nname: reviewer\ndescription: Reviews.\naccess: read-only\n---\n\n# Reviewer\n\n- Read only.\n',
    '.agents/agents/implementer.md': '---\nname: implementer\ndescription: Implements.\naccess: read-write\n---\n\n# Implementer\n\n- Follow the [base rule](../rules/base.md), the [standard](../../docs/x.md#y) and [the web](https://example.com).\n',
    '.agents/hooks/guard.mjs': '',
    '.agents/skills/alpha/SKILL.md': '---\nname: alpha\n---\n',
    '.agents/skills/beta/SKILL.md': '---\nname: beta\n---\n',
    '.agents/skills/README.md': '# Skills\n',
    '.agents/harness.config.json': JSON.stringify({ productionCommands: PRODUCTION_COMMANDS.map((command) => ({ command, effect: 'x' })) }),
    '.claude/settings.json': JSON.stringify({ permissions: { allow: ['Bash(gh pr create:*)'], ask: PRODUCTION_COMMANDS.map((command) => `Bash(${command}:*)`) }, hooks: { Stop: [] } }),
  };
  for (const [file, content] of Object.entries(files)) {
    mkdirSync(path.dirname(path.join(root, file)), { recursive: true });
    writeFileSync(path.join(root, file), content);
  }
  const manifest = {
    version: 1,
    entries: [
      { id: 'rules-base', kind: 'rule', source: '.agents/rules/base.md', targets: { claude: '.claude/rules/base.md', codex: null }, note: 'anchor' },
      { id: 'agent-reviewer', kind: 'agent', source: '.agents/agents/reviewer.md', targets: { claude: '.claude/agents/reviewer.md', codex: '.codex/agents/reviewer.toml' } },
      { id: 'agent-implementer', kind: 'agent', source: '.agents/agents/implementer.md', targets: { claude: '.claude/agents/implementer.md', codex: '.codex/agents/implementer.toml' } },
      { id: 'skills', kind: 'skill', source: '.agents/skills', targets: { claude: '.claude/skills', codex: null }, note: 'native' },
      { id: 'hook-guard', kind: 'hook', source: '.agents/hooks/guard.mjs', targets: { claude: '.claude/settings.json', codex: '.codex/hooks.json' }, options: { claude: [{ event: 'PreToolUse', matcher: 'Bash', timeout: 30 }], codex: [{ event: 'PreToolUse', timeout: 30 }] } },
    ],
  };
  writeFileSync(path.join(root, '.agents/manifest.json'), JSON.stringify(manifest));
  return root;
}

const read = (root, file) => readFileSync(path.join(root, file), 'utf8');

describe('sync-adapters', () => {
  it('generates clean adapters from the packaged harness', () => {
    const root = installed();
    expect(write(root)).toEqual([]);
    expect(check(root)).toEqual([]);
    expect(read(root, '.codex/agents/reviewer.toml')).toMatch(/^# Generated by \.agents\/sync-adapters\.mjs from \.agents\/agents\/reviewer\.md\. Edit the source, then run node \.agents\/sync-adapters\.mjs\.\n/);
    const commands = Object.values(JSON.parse(read(root, '.claude/settings.json')).hooks).flat().flatMap((group) => group.hooks.map((handler) => handler.command));
    expect(commands.length).toBeGreaterThan(0);
    for (const command of commands) expect(command).toMatch(/"\$CLAUDE_PROJECT_DIR\/\.agents\/hooks\/[a-z-]+\.(?:mjs|sh)"/);
    for (const command of commands) expect(existsSync(path.join(root, /\.agents\/hooks\/[a-z-]+\.(?:mjs|sh)/.exec(command)[0]))).toBe(true);
  });

  it('asks for an ask rule per production command of the config, and writes nothing without them', () => {
    const root = installed({ productionCommands: [{ command: 'acme deploy', effect: 'deploys production' }] });
    expect(write(root)).toEqual(['.claude/settings.json: permissions.ask needs Bash(acme deploy:*), a production command (docs/agent-harness.md#production-confirmations)']);
    expect(existsSync(path.join(root, '.claude/settings.json'))).toBe(false);
    mkdirSync(path.join(root, '.claude'));
    writeFileSync(path.join(root, '.claude/settings.json'), JSON.stringify({ permissions: { ask: ['Bash(acme deploy:*)'] } }));
    expect(write(root)).toEqual([]);
    expect(check(root)).toEqual([]);
  });

  it('writes adapters that then pass the check', () => {
    const root = harness();
    expect(check(root).length).toBeGreaterThan(0);
    expect(write(root)).toEqual([]);
    expect(check(root)).toEqual([]);
    expect(read(root, '.claude/rules/base.md')).toBe(read(root, '.agents/rules/base.md'));
  });

  it('generates hooks for both tools and keeps the hand-maintained permissions', () => {
    const root = harness();
    write(root);
    const settings = JSON.parse(read(root, '.claude/settings.json'));
    expect(settings.permissions.allow).toEqual(['Bash(gh pr create:*)']);
    expect(settings.hooks).toEqual({ PreToolUse: [{ matcher: 'Bash', hooks: [{ type: 'command', command: 'node "$CLAUDE_PROJECT_DIR/.agents/hooks/guard.mjs" --tool claude', timeout: 30 }] }] });
    expect(JSON.parse(read(root, '.codex/hooks.json')).hooks.PreToolUse[0].hooks[0].command).toBe('f="$(git rev-parse --show-toplevel)/.agents/hooks/guard.mjs"; [ -f "$f" ] || exit 0; node "$f" --tool codex');
    expect(read(root, '.codex/config.toml')).toMatch(/sandbox_mode = "workspace-write"\napproval_policy = "on-request"/);
  });

  it('maps agent access to each tool', () => {
    const root = harness();
    write(root);
    expect(read(root, '.claude/agents/reviewer.md')).toMatch(/^---\nname: reviewer\ndescription: Reviews\.\ntools: Read, Grep, Glob, Bash, WebFetch, WebSearch\n---\n/);
    expect(read(root, '.claude/agents/implementer.md')).not.toMatch(/^tools:/m);
    expect(read(root, '.codex/agents/reviewer.toml')).toMatch(/sandbox_mode = "read-only"\ndeveloper_instructions = '''\n# Reviewer/);
    expect(read(root, '.codex/agents/implementer.toml')).toMatch(/sandbox_mode = "workspace-write"/);
  });

  it('reports hand edits, stale files and a changed source', () => {
    const root = harness();
    write(root);
    writeFileSync(path.join(root, '.claude/rules/base.md'), 'edited by hand\n');
    writeFileSync(path.join(root, '.claude/rules/old.md'), 'stale\n');
    writeFileSync(path.join(root, '.agents/agents/reviewer.md'), read(root, '.agents/agents/reviewer.md').replace('Read only.', 'Read only, always.'));
    const drift = check(root);
    expect(drift).toContain('.claude/rules/base.md: differs from its source');
    expect(drift).toContain('.claude/rules/old.md: not generated from any manifest entry');
    expect(drift).toContain('.claude/agents/reviewer.md: differs from its source');
    expect(drift).toContain('.agents/manifest.state.json: differs from its source');
    write(root);
    expect(existsSync(path.join(root, '.claude/rules/old.md'))).toBe(false);
    expect(check(root)).toEqual([]);
  });

  it('fails on an allow rule that covers a production command, and on a missing ask rule', () => {
    const ask = PRODUCTION_COMMANDS.map((command) => `Bash(${command}:*)`);
    expect(permissionProblems({ ask, allow: ['Bash(gh pr merge:*)', 'Bash(acme deploy:*)', 'Bash', 'Bash(gh pr create:*)', 'Read'] }, PRODUCTION_COMMANDS)).toHaveLength(3);
    expect(permissionProblems({ ask, allow: ['Bash(acme:*)'] }, PRODUCTION_COMMANDS)[0]).toMatch(/acme db push/);
    expect(permissionProblems({ ask }, PRODUCTION_COMMANDS)).toEqual([]);
    expect(permissionProblems({ ask: ask.slice(1) }, PRODUCTION_COMMANDS)).toEqual([`.claude/settings.json: permissions.ask needs ${ask[0]}, a production command (docs/agent-harness.md#production-confirmations)`]);
    // The guarded merge never gets an allow rule, with or without production commands.
    expect(permissionProblems({ allow: ['Bash(gh pr merge:*)'] })).toHaveLength(1);
  });

  it('keeps hand edits to permissions out of the drift check', () => {
    const root = harness();
    write(root);
    const settings = JSON.parse(read(root, '.claude/settings.json'));
    settings.permissions.allow.push('Bash(ls:*)');
    writeFileSync(path.join(root, '.claude/settings.json'), `${JSON.stringify(settings, null, 2)}\n`);
    expect(check(root)).toEqual([]);
  });

  it('rewrites relative links of generated roles to still reach their files', () => {
    const root = harness();
    write(root);
    expect(read(root, '.claude/agents/implementer.md')).toContain('[base rule](../../.agents/rules/base.md), the [standard](../../docs/x.md#y) and [the web](https://example.com)');
    expect(read(root, '.codex/agents/implementer.toml')).toContain('[base rule](.agents/rules/base.md), the [standard](docs/x.md#y) and [the web](https://example.com)');
  });

  it.each([
    ['a missing source', (entries) => entries.push({ id: 'rules-gone', kind: 'rule', source: '.agents/rules/gone.md', targets: { claude: '.claude/rules/gone.md', codex: null }, note: 'x' }), /source \.agents\/rules\/gone\.md is missing/],
    ['an unknown kind', (entries) => entries.push({ id: 'rules-odd', kind: 'script', source: '.agents/rules/base.md', targets: { claude: '.claude/rules/odd.md', codex: null }, note: 'x' }), /unknown kind script/],
    ['a duplicate target', (entries) => entries.push({ id: 'rules-again', kind: 'rule', source: '.agents/rules/base.md', targets: { claude: '.claude/rules/base.md', codex: null }, note: 'x' }), /already generated by rules-base/],
    ['a target escaping the repository', (entries) => entries.push({ id: 'rules-out', kind: 'rule', source: '.agents/rules/base.md', targets: { claude: '.claude/../../etc/x', codex: null }, note: 'x' }), /must stay under \.claude\//],
    ['a directory source for a rule', (entries) => entries.push({ id: 'rules-dir', kind: 'rule', source: '.agents/skills', targets: { claude: '.claude/rules/dir.md', codex: null }, note: 'x' }), /a rule source must be a file/],
  ])('reports %s instead of writing it', (_label, mutate, message) => {
    const root = harness();
    const manifest = JSON.parse(read(root, '.agents/manifest.json'));
    mutate(manifest.entries);
    writeFileSync(path.join(root, '.agents/manifest.json'), JSON.stringify(manifest));
    const { files, problems } = generate(root);
    expect(problems.join('\n')).toMatch(message);
    expect(write(root).join('\n')).toMatch(message);
    expect(existsSync(path.join(root, '.claude/rules/base.md'))).toBe(false);
    expect([...files.keys()].some((file) => file.includes('..') || file.endsWith('odd.md') || file.endsWith('dir.md'))).toBe(false);
  });

  it('runs the check through a symlinked path instead of exiting 0 without checking', () => {
    const root = installed();
    expect(write(root)).toEqual([]);
    const link = path.join(harness(), 'sync.mjs');
    symlinkSync(path.join(root, '.agents/sync-adapters.mjs'), link);
    expect(execFileSync('node', [link, '--check'], { encoding: 'utf8', stdio: 'pipe' })).toMatch(/Agent adapters match \.agents\//);
  });

  it('requires a manifest entry for every instinct', () => {
    const root = harness();
    mkdirSync(path.join(root, '.agents/instincts'));
    writeFileSync(path.join(root, '.agents/instincts/shared-index.md'), '# Shared index\n');
    expect(write(root)).toEqual(['.agents/manifest.json: .agents/instincts/shared-index.md has no instinct entry, so the anchor hook never loads it']);
  });
});

describe('.claude/skills symlinks', () => {
  it('links one entry per skill to its source directory', () => {
    const root = harness();
    write(root);
    expect(check(root)).toEqual([]);
    expect(readdirSync(path.join(root, '.claude/skills')).sort()).toEqual(['alpha', 'beta']);
    expect(readlinkSync(path.join(root, '.claude/skills/alpha'))).toBe('../../.agents/skills/alpha');
    expect(lstatSync(path.join(root, '.claude/skills/alpha')).isSymbolicLink()).toBe(true);
    expect(existsSync(path.join(root, '.claude/skills/alpha/SKILL.md'))).toBe(true);
  });

  it('reports a copied skill directory and a wrong link', () => {
    const root = harness();
    write(root);
    rmSync(path.join(root, '.claude/skills/alpha'));
    mkdirSync(path.join(root, '.claude/skills/alpha'));
    rmSync(path.join(root, '.claude/skills/beta'));
    symlinkSync('../elsewhere/beta', path.join(root, '.claude/skills/beta'));
    expect(check(root)).toEqual(expect.arrayContaining([
      '.claude/skills/alpha: must be a symlink to ../../.agents/skills/alpha',
      '.claude/skills/beta: links to ../elsewhere/beta, expected ../../.agents/skills/beta',
    ]));
  });

  // Shared skills are optional: without .agents/skills, the repository's own
  // .claude/skills is not the generator's to clean.
  it('leaves .claude/skills alone when .agents/skills is absent', () => {
    const root = harness();
    rmSync(path.join(root, '.agents/skills'), { recursive: true });
    mkdirSync(path.join(root, '.claude/skills/own'), { recursive: true });
    writeFileSync(path.join(root, '.claude/skills/own/SKILL.md'), '---\nname: own\n---\n');
    expect(write(root)).toEqual([]);
    expect(check(root)).toEqual([]);
    expect(existsSync(path.join(root, '.claude/skills/own/SKILL.md'))).toBe(true);
  });
});
