#!/bin/sh
# Generate ~/.codex/AGENTS.md from the canonical ~/.agents/AGENTS.md.
# Codex does not expand `@` imports, so the RTK rule (~/.codex/RTK.md, owned by
# `rtk init`) is inlined instead of referenced.
#
#   sync-codex-agents.sh          write the generated file
#   sync-codex-agents.sh --check  exit 1 if the generated file is stale or hand-edited
set -eu

SRC="${AGENTS_SOURCE:-$HOME/.agents/AGENTS.md}"
RTK="$HOME/.codex/RTK.md"
OUT="$HOME/.codex/AGENTS.md"

[ -r "$SRC" ] || { echo "sync-codex-agents: missing $SRC" >&2; exit 2; }

render() {
  printf '%s\n\n' '<!-- GENERATED by user-level/sync-codex-agents.sh from ~/.agents/AGENTS.md and ~/.codex/RTK.md. Do not edit: edit the sources, then rerun the script. -->'
  cat "$SRC"
  if [ -r "$RTK" ]; then
    printf '\n'
    # Demote RTK.md one heading level so it nests under this file's H1.
    sed -E 's/^(#+) /\1# /' "$RTK"
  fi
}

tmp=$(mktemp "${OUT}.XXXXXX")
trap 'rm -f "$tmp"' EXIT
render > "$tmp"

if [ "${1-}" = "--check" ]; then
  if cmp -s "$tmp" "$OUT"; then exit 0; fi
  echo "sync-codex-agents: $OUT is out of date; run user-level/sync-codex-agents.sh" >&2
  exit 1
fi

chmod 600 "$tmp"
mv "$tmp" "$OUT"
trap - EXIT
echo "sync-codex-agents: wrote $OUT"
